name: QuteFuzz CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      RUN_MODE: CI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Setup Script
        run: |
          python3 -m scripts.setup

      - name: Formatting
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run pyright

      - name: Run CI Pipeline
        run: uv run -m scripts.run --num-tests 3 --grammars pytket qiskit pennylane cirq
